title: "Passkey Directory"
copyright: "2factorauth"
languageCode: "en"
DefaultContentLanguage: "en"
disableKinds: ["taxonomy"]
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true

params:
  default:
    description: "Directory of sites with passkeys support"
    github: "2factorauth/passkeys"
    theme_color: "#38CCCC"
    icon_path: "https://passkeys-api.2fa.directory/icons/"
    mastodon: "https://infosec.exchange/@2factorauth"

  twitter:
    handle: "2faorg"
    card: "https://i.imgur.com/92cAVal.png"

outputFormats:
  manifest:
    name: "manifest"
    baseName: "manifest"
    mediaType: "application/json"
    notAlternative: true

outputs:
  home:
    - "MANIFEST"
markup:
  goldmark:
    renderer:
      unsafe: true
