title: "Passkey Directory"
copyright: "2factorauth"
languageCode: "en"
DefaultContentLanguage: "en"
disableKinds: ["taxonomy"]
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true

params:
  default:
    description: "List of sites with passkeys support."
    github: "2factorauth/passkeys"
    theme_color: "#38CCCC"
    icon_path: "https://api.passkeys.2fa.directory/icons/"
    mastodon: "https://infosec.exchange/@2factorauth"

  twitter:
    handle: "2faorg"
    card: "/icons/social-card.png"

outputFormats:
  manifest:
    name: "manifest"
    baseName: "manifest"
    mediaType: "application/json"
    notAlternative: true

outputs:
  home:
    - "MANIFEST"
